# Generated by Django 5.2.7 on 2025-11-21 20:30

import umd_handle.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_handle_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='url',
            field=models.CharField(validators=[umd_handle.api.models.validate_url]),
        ),
    ]
